### ISSUE TITLE
Are there plans to bring banking.stupig.org back online?

### ISSUE THREAD

**Issue by mark-langer** [opendata-stuttgart/banking-api#4]
Hi there!

I hope this is the right place to post this. Are there any plans to bring the API at banking.stupig.org back online? Thanks for providing it in the first place!

**Comment by mfa** [comment]
no. sorry. I don't need it anymore and don't want to keep it up-to-date.

**Comment by mark-langer** [comment]
That's too bad. Thanks for providing it so far!

**Comment by mfa** [comment]
I was experimenting with datasette and wrote a converter for the bundesbank xlsx to sqlite: https://github.com/mfa/bundesbank-to-sqlite

maybe this is a simple way to bring the api back

**Comment by mark-langer** [comment]
Thanks for the script.

Although we're using a JS stack instead of Python and a NoSQL DB instead of the SQL-based SQLite, the link to the Bundesbank .xlsx file is very useful to us to bring it back ourselves.
